import Head from "next/head";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h1 className="text-5xl text-center mt-10" >Welcome to the website</h1>
                <h3 className="text-xl text-center mt-5 px-24">Learn how to implement authentication in React</h3>
            </main>
        </div>
    );
}
